### ISSUE TITLE
Fail to build src/make_vector_tile.lo 

### ISSUE THREAD

**Issue by dmarteau** [MapQuest/avecado#71]
Trying to build avocado out of the box fails: 

On ubuntu 15.04
g++ 4.9.2
Using branch master for avocado
Using  branch master for mapnik-vector-tile as git submodule

./configure is successfull
calling 'make' produce the following error:

``` bash
# make
make  all-am
make[1]: Entering directory '/home/dmarteau/projets/mappy/git-lbs/avecado'
  CXX      src/make_vector_tile.lo
In file included from src/make_vector_tile.cpp:7:0:
mapnik-vector-tile/src/vector_tile_processor.hpp:13:23: fatal error: clipper.hpp: No such file or directory
 #include "clipper.hpp"
                       ^
compilation terminated.
Makefile:1323: recipe for target 'src/make_vector_tile.lo' failed
make[1]: *** [src/make_vector_tile.lo] Error 1
make[1]: Leaving directory '/home/dmarteau/projets/mappy/git-lbs/avecado'
Makefile:807: recipe for target 'all' failed
make: *** [all] Error 2
```

Include path problem ?

Note that building stand alone mapnik-vector-tile (i.e cd  mapnik-vector-tile && make) is succeessfull.

**Comment by pnorman** [comment]
This looks like a wrong mapnik version problem. What version of Mapnik did you use?

**Comment by zerebubuth** [comment]
On 15.04, I'm getting a similar message:

```
$ make
make  all-am
make[1]: Entering directory '/home/matt/Programming/Personal/avecado'
  CXX      src/make_vector_tile.lo
In file included from mapnik-vector-tile/src/vector_tile_processor.hpp:87:0,
                 from src/make_vector_tile.cpp:7:
mapnik-vector-tile/src/vector_tile_processor.ipp:30:30: fatal error: agg_conv_clipper.h: No such file or directory
compilation terminated.
Makefile:1332: recipe for target 'src/make_vector_tile.lo' failed
make[1]: *** [src/make_vector_tile.lo] Error 1
make[1]: Leaving directory '/home/matt/Programming/Personal/avecado'
Makefile:817: recipe for target 'all' failed
make: *** [all] Error 2
```

This is with `libmapnik-dev` 3.0.3+ds-1 installed from Ubuntu repos. That header appears to be installed by the older mapnik 2.2 development package, but still depends on `clipper.hpp`. I think I remember that coming from a vendored submodule, but it'll take me more time to dig into it.

**Comment by dmarteau** [comment]
I Use a home built mapnik from v3.0.9 tag.
The clipper.hpp file is located in  mapnik-vector-tile/deps/clipper/cpp/clipper.hpp (pulled by mapnik-vector-tile/Makefile .deps/clipper rule). 
mapnik-vector-tile can be built directly without problem but fails when driven by avecado build.

**Comment by zerebubuth** [comment]
I've had a go at fixing this, but it looks like a _lot_ has changed in Mapnik in the past 6 months, despite it only having had point releases. I haven't been able to get it working again - it doesn't even compile - but my current work is on a [branch](https://github.com/zerebubuth/avecado/tree/update_mapnik_303).

I'm not even sure whether it would be simpler to throw `avecado` away and start again with the new Mapnik geometry classes than try to port this code. Either way, it's a lot of work :disappointed:

**Comment by pnorman** [comment]
> despite it only having had point releases

I thought the changes were between what we had and Mapnik 3.0.0, not in the point releases

**Comment by zerebubuth** [comment]
> I thought the changes were between what we had and Mapnik 3.0.0, not in the point releases

Oh, you're probably right - changes between Mapnik 3.x-pre and 3.0.0 don't really count as "point releases". Probably wasn't an up-to-date "pre" version, even. One of those things where updating it was always on the TODO, but never important enough to get scheduled.

**Comment by dmarteau** [comment]
Not relevant anymore.
